# ConnectChain Configuration

# OpenAI Configuration
openai:
  api_key: "your_openai_api_key_here"
  model: "gpt-3.5-turbo"
  max_tokens: 150
  temperature: 0.7

# Azure OpenAI Configuration
azure:
  endpoint: "https://your-azure-openai-resource.openai.azure.com/"
  api_key: "your_azure_openai_api_key_here"
  deployment_name: "your_deployment_name"

# LLM Provider Selection
llm:
  provider: "openai"  # Options: "openai" or "azure"

# Proxy Configuration
proxy:
  http:
    host: "proxy.example.com"
    port: 8080
  https:
    host: "proxy.example.com"
    port: 8443

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/connectchain.log"
  max_size: 10MB
  backup_count: 5

# Chain Configuration
chain:
  max_retries: 3
  retry_delay: 1000  # milliseconds

# Security Settings
security:
  input_sanitization: true
  output_validation: true

# Performance Settings
performance:
  cache_enabled: true
  cache_size: 1000
  thread_pool_size: 4

# Custom Prompts
prompts:
  default: "You are a helpful AI assistant. Please answer the following question: {{question}}"
  system: "You are an AI language model trained to assist with various tasks."

# API Rate Limiting
rate_limit:
  requests_per_minute: 60
  burst: 10